### ISSUE TITLE
After disconnecting a client, the result is always BadNotConnected

### ISSUE THREAD

**Issue by Ttberg** [nauful/LibUA#10]
The title says it all, after opening a secure channel with security Policy set to none to get the endpoints, I disconnect the client but always get a BadNotConnected as a return value. I was expecting after a successful disconnect to receive the Good result.

**Comment by nauful** [comment]
This is a design choice to keep the return value of any UA calls as the current server state. Different UA servers have many compatibility workarounds, and the most common denominator is to simply close the socket. Sending a close message is to just hint that the server doesn't need to keep around client-specific information (such as subscriptions) preserved if the client reconnects.
