### ISSUE TITLE
BadCertificateInvalid when using UaExpert

### ISSUE THREAD

**Issue by rsr-maersk** [nauful/LibUA#100]
Hi, thanks for the great OPC server.

When connecting to demo server using UaExpert i get a BadCertificateInvalid. Is this a server or client issue?
If it is the server, any idea how to fix?

Thanks again!

**Comment by nauful** [comment]
Likely a server configuration issue.

Please test using these: https://github.com/nauful/LibUA/files/4586442/lubua-clntsrvcert.zip

If you still see the error, can you upload your uaexpert client for me to test?

**Comment by rsr-maersk** [comment]
Sorry, stupid question here.  it this right? It is throwing on the xca
![image](https://user-images.githubusercontent.com/76153851/194335669-eafc3dc3-f0d3-499b-bd72-42c88193852d.png)

**Comment by nauful** [comment]
Hmm, I thought that would have worked. I guess not.

If you share the client for uaexpert here, I can take a look at the original problem with the self-generated certificate.

**Comment by generik0** [comment]
I dont know if it will work, because "var rsaPrivateParams1 = UASecurity.ImportRSAPrivateKey(File.ReadAllText("libUA_Client_And_ServerCert_Example.xca"));" returns null, (the file is present in bin)

Is this correct code?

`appCertificate = new X509Certificate2("libUA_ClientAndServerCert_Example.cer");
        cryptPrivateKey = new RSACryptoServiceProvider(DwKeySize);
        var rsaPrivateParams1 = UASecurity.ImportRSAPrivateKey(File.ReadAllText("libUA_Client_And_ServerCert_Example.xca"));
        cryptPrivateKey.ImportParameters(rsaPrivateParams1);

        return (appCertificate, cryptPrivateKey);`

**Comment by nauful** [comment]
No they have to be converted to pem and der format: https://github.com/nauful/LibUA/issues/94#issuecomment-1243628517

Alternatively you might change the certificate and key loading code. It's old .NET and there are probably better ways now.

**Comment by generik0** [comment]
> Please test using these: https://github.com/nauful/LibUA/files/4586442/lubua-clntsrvcert.zip

Ok, i am really stupid, i am sorry. You recommended i use the lubua-clntsrvcert. How and where do i use them. This is proably what i should have started by asking

**Comment by nauful** [comment]
You would have to convert them to pem and der format as above, then replace the existing files in bin with the new converted files. Shouldn't need any code changes.

**Comment by nauful** [comment]
For the original question at the top, I need a copy of the client to run and investigate why it doesn't accept the self generated certificate.

**Comment by generik0** [comment]
Ahh, OK, its UaExpert from unified-automation.com: https://www.unified-automation.com/downloads/opc-ua-clients.html

**Comment by generik0** [comment]
the size is to large, even with UTLRA compression

**Comment by generik0** [comment]
[uaexpert-bin-win32-x86-vs2008sp1-v1.6.2-438.zip](https://github.com/nauful/LibUA/files/9739437/uaexpert-bin-win32-x86-vs2008sp1-v1.6.2-438.zip)

**Comment by generik0** [comment]
PLease let me know when you have grabbed it. I will delete it.. Again. Thanks 1 mill for your time

**Comment by nauful** [comment]
I have downloaded, will investigate in a bit.

**Comment by nauful** [comment]
Done, update and check if it works now: https://github.com/nauful/LibUA/commit/7c591acbe7b0faaa51dc34e5b0a520e26fa202e0

![image](https://user-images.githubusercontent.com/50109829/194727790-6435295b-e2ab-4ec9-9d33-548210414904.png)

**Comment by generik0** [comment]
Has helped! Great! :-)
Now for the second warning: 
![image](https://user-images.githubusercontent.com/2411563/194741635-484abdc4-cebd-4702-a1de-a13e46829cae.png)

BadCertificateUseNotAllowed. Any thoughts?

**Comment by generik0** [comment]
Also when using user/pw this throws 
![image](https://user-images.githubusercontent.com/2411563/194742011-b4ff9a52-e83c-4f41-8a63-f6eb36c05167.png)

**Comment by nauful** [comment]
BadCertificateUseNotAllowed is probably because uaexpert is looking for a certificate authority tree or some other signature in the self-generated certificate. If you convert your own to pem and der format, you can load those instead and use those.

When using your own, remember to set up a local CA: https://medium.com/coding-snippets/acting-as-a-certificate-authority-with-openssl-a0d71b17bc95

For UserNameIdentityToken, try the latest now: https://github.com/nauful/LibUA/commit/810d93722e9575736e809e24658c872f1d2badad

**Comment by generik0** [comment]
I will check it out latest tomorrow evening. Sorry for the delay.

**Comment by generik0** [comment]
@nauful yes, teh erxception is now gone. great work. thanks!

**Comment by nauful** [comment]
By the way, if you are using this library for any projects, there is no obligation but I would be very interested in hearing where and how. I would appreciate your permission to use that information in my list of use cases. You can email me at my username @gmail.com

**Comment by generik0** [comment]
Let me see what I can WIP up in the weekend.
