### ISSUE TITLE
FindServers1 differs from GetEndpoints

### ISSUE THREAD

**Issue by generik0** [nauful/LibUA#101]
Hi again

Sorry for disturbing you again, with another client issue

The following is being reported by a Siemens PLC ua client.

Any thoughts?
![image](https://user-images.githubusercontent.com/2411563/194917624-3e1ba1e4-39ed-4d90-82a9-0ace5b51da61.jpeg)

No idea is a fair enough answer :-)

**Comment by generik0** [comment]
I also get it on the demo lib, with LibUa core, when using teh discovery 
![image](https://user-images.githubusercontent.com/2411563/194930818-04e91ad9-7093-460c-bc28-477c37f2ba48.png)

**Comment by nauful** [comment]
In the sample application:
```
uaAppDesc = new ApplicationDescription(
	"urn:DemoApplication", "http://quantensystems.com/",
	new LocalizedText("en-US", "QuantenSystems demo server"), ApplicationType.Server,
	null, null, null);
```

The last parameter can provide an array of discovery server urls if you need that e.g. server endpoint for connection is different from the one used for discovery. This is usually unnecessary unless you have a discovery server, `ApplicationType.DiscoveryServer`, separate from your normal server.

This is the server handler for GetEndpoints:
`public override IList<EndpointDescription> GetEndpointDescriptions(string endpointUrlHint)`

This is the server handler for FindServers:
`public override ApplicationDescription GetApplicationDescription(string endpointUrlHint)`

**Comment by generik0** [comment]
Hi @nauful thats perfect thanks!

I might make a PR so we don't get this warning ie add to the demo server. Ok?
