### ISSUE TITLE
AccessLevelEx Invalid datatype OpcUaTypeUint32, Received OpcUa_Byte

### ISSUE THREAD

**Issue by generik0** [nauful/LibUA#102]
Hi @nauful 

Sorry to disturb you again, still having trouble with a rather strict client.  

AccessLevelEx Invalid datatype OpcUaTypeUint32, Received OpcUa_Byte

![image](https://user-images.githubusercontent.com/2411563/195393274-56825a9d-0669-451b-8a69-b746416cedad.png)

It seems the ArrayDimenstions should also be UInt32 Arrary[-1]

He is an example of the information in a server that is working. To me the array dimensions and the AccessLevelEx seams to be different

![image](https://user-images.githubusercontent.com/2411563/195394842-27cf4c16-8ebc-4615-8d74-551fff7d6f90.png)

Any thoughts?

**Comment by nauful** [comment]
I'll investigate, this should be a quick one. Is `uaexpert-bin-win32-x86-vs2008sp1-v1.6.2-438` still valid as a test client?

**Comment by nauful** [comment]
This should fix the error: https://github.com/nauful/LibUA/commit/bb2c24b02887be40f3c4cb16b7d193f0c1dbf0d8

For ArrayDimensions I would expect `BadAttributeInvalidId` to work, but let me know if that still causes a problem and I can continue digging.

**Comment by generik0** [comment]
Thanks @nauful !!! that helpes that issue., Will close here and open another up if more issues arrise

**Comment by nauful** [comment]
Whenever you have time, I would definitely like to hear more about your use cases with this library and where it's being used.

**Comment by generik0** [comment]
@nauful you dont Seem to have an email on your profile

**Comment by nauful** [comment]
nauful@gmail
