### ISSUE TITLE
Client lacking TransferSubscriptions for re-establish connections

### ISSUE THREAD

**Issue by wckivX** [nauful/LibUA#103]
Section 6.7 Re-establishing Connections of the OPC UA online reference:

https://reference.opcfoundation.org/v105/Core/docs/Part4/6.7/

may require the client to issue TransferSubscriptions and Republish.  Both calls are not currently supported as fuctions in LibUA.

Can these calls be added?

**Comment by nauful** [comment]
Both server and client discard all session information on disconnect right now. This would need some additional handling for a duration after a session is lost and handling for memory and security restrictions e.g. connect 50 sessions one at a time and make 100 subscriptions rapidly -> 5000 extra subscription info objects left in memory for a while.

I may revisit this in the future but I don't have time to make those changes any time soon.
