### ISSUE TITLE
Sampels for NodeMethod

### ISSUE THREAD

**Issue by techworked** [nauful/LibUA#105]
Hi, is there any samples on how to use NodeMethod and calling the function to get return value.

**Comment by nauful** [comment]
Some solutions:
https://github.com/nauful/LibUA/issues/23
https://github.com/nauful/LibUA/issues/29

**Comment by nauful** [comment]
Please re-open if you have additional questions.

**Comment by techworked** [comment]
Thanks will try first. Thanks for creating this library
