### ISSUE TITLE
Alarm Interactions Via Client

### ISSUE THREAD

**Issue by dstickel** [nauful/LibUA#106]
Has it been implemented to interact with alarms from the client? Examples would be acknowledging the alarm.

Is creating a client.HistoryRead using ReadEventDetails and HistoryReadValueId, like in the sample client, required for using alarms or what would be required if not? I know you need the EventNotification but is there a generic ReadValueId that can be used for the MonitoredItemCreateRequest that will observe all alarms on the client side?

**Comment by nauful** [comment]
There are alarms as part of the test server, but I haven't done anything for alarms on the client side. The last time I tried, I couldn't get anything generic to work similarly across different server vendors.

**Comment by dstickel** [comment]
Ok thanks.
