### ISSUE TITLE
Semaphore race condition with later client Connect calls

### ISSUE THREAD

**Issue by wckivX** [nauful/LibUA#107]
The Connect method of Client.cs creates a new Semaphore (cs) each time it is called. It should only create a new Semaphore if cs is null.

Existing Client.cs code:

cs = new Semaphore(1, 1);

Proposed change:

if (null == cs) { cs = new Semaphore(1, 1); }

If a second call to Connect is made, concurrent method calls using cs for synchronization can have their cs Semaphore changed to a new instance.  This probably only triggers on poorly written code.

**Comment by nauful** [comment]
A few other variables would also need to be cleaned. Cleaner fix: https://github.com/nauful/LibUA/commit/20e63854a01b98d968af69a72465a6833b316b2f
