### ISSUE TITLE
LibUA only supports obsolete security policies

### ISSUE THREAD

**Issue by Ttberg** [nauful/LibUA#11]
According to the OPC foundation, the security policies Basic256 and Basic128Rsa15 are obsolete. Is there any plan to implement e.g. Basic256Sha256?

**Comment by nauful** [comment]
Support will likely be added for this in the future but I don't have time at the moment to resume development beyond bug fixes and support. I'd invite anyone with the time to investigate, implement and test to create a pull request that implements new security policies. Right now the only implemented policies are None, Basic256 and Basic128Rsa15.

Security.cs contains implementations for the signing and encryption schemes if you'd like to try adding support.

Closing the issue for now, will re-open and resolve when support is added, either via contributor or when I get time to investigate.

**Comment by nauful** [comment]
Started adding support for Basic256Sha256 as a security policy:
https://github.com/nauful/LibUA/tree/prototype_security_basic256sha256
