### ISSUE TITLE
Server application certificate error on connecting client with username/pwd

### ISSUE THREAD

**Issue by jsmit1982** [nauful/LibUA#110]
Hi, 

First of all thank you very much for this library! It is the only one that actually works great in Unity (.NET 2.0 Standard). 
I have one challenge using the server part though. OpcWatch is able to connect without any issue when using Anonymous mode, but when I try to use username/password the connection is closed and OpcWatch indicates ApplicationCertificate cannot be found. Any idea how that may be? And how to resolve?

Thanks for your support and apologies if this is a stupid question!

**Comment by nauful** [comment]
Hello and glad to hear my library helps you.

Can you please upload a Wireshark capture? It is possible that OpcWatch is whitelisting certificates. In this case I think you have to add your public certificate file, which you use load into the server, to OpcWatch's whitelist.

You may need to whitelist this file:
https://github.com/nauful/LibUA/blob/2e73c7b045cbaec493eb09531407bc2bbf78e16e/NET%20Core/TestServer/Program.cs#L470

By the way, if you are using this library for any projects, there is no obligation but I would be very interested in hearing where and how. I would appreciate your permission to use that information in my list of use cases. If you prefer email, my email is my username @gmail.com

Thanks

**Comment by nauful** [comment]
Implemented more security policies and user identity token signatures (rsa-oaep) here:
https://github.com/nauful/LibUA/commit/6534b413b5abaca258542aabd81cf85094c18838

Let me know if you have any problems.
