### ISSUE TITLE
Possible null dereference when throwing exceptions in NetDispatcher

### ISSUE THREAD

**Issue by smitha-cgi** [nauful/LibUA#112]
In a couple of places there is code like this:

```
var respVals = app.HandleWriteRequest(config.Session, writeValues);
if (respVals == null || respVals.Length != writeValues.Length)
{
    throw new Exception(string.Format("Write requested {0} ids, returned {1} response status codes", writeValues.Length, respVals.Length));
}
```

If respVals is null here then an unhandled exception will occur when attempting to access its Length property

**Comment by nauful** [comment]
There is already a check for `respVals == null` which throws a different exception. This seems to be working fine.
