### ISSUE TITLE
Calling an opc method which takes a complex server type as a parameter

### ISSUE THREAD

**Issue by kitog** [nauful/LibUA#118]
I'm trying to call a method on an OPC-UA server which takes a server defined DataType. Is this supported by this library?

The DataType I need to pass in is of type OpcVariableItem which look as follows when I view it with UaExpert client:

![image](https://user-images.githubusercontent.com/659474/227580433-7208dd60-11e8-438c-94bc-d6d4283993fa.png)

**Comment by nauful** [comment]
Look at the method for `Call`:
https://github.com/nauful/LibUA/blob/ca0c99e0b2ddbedb97fd2164cad1f4dd30a74a68/NET%20Core/LibUA/Client.cs#L3422

Input parameters can be any type of `Variant`:
https://github.com/nauful/LibUA/blob/ca0c99e0b2ddbedb97fd2164cad1f4dd30a74a68/NET%20Core/LibUA/Client.cs#L3455

If that needs a full structure, you should look at serializing (using `MethodBuffer`) into an `ExtensionObject` instance and writing that. You would probably implement a custom `Call` method and replace `VariantEncode` and `VariantDecode` with serializers and deserializers for your custom types.

`DemoClient` extends `Client`:
https://github.com/nauful/LibUA/blob/ca0c99e0b2ddbedb97fd2164cad1f4dd30a74a68/NET%20Core/TestClient/Program.cs#L16
So you could add this new method there.

Let me know if you have any questions about any part of this and I help further.
