### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by nurgaleevarman** [nauful/LibUA#128]
Hi!
How create subfolders?
In examples created root folders

**Comment by nauful** [comment]
Hello,

Here you can see how a folder (Items) is created and linked to Objects:
https://github.com/nauful/LibUA/blob/7e1445072a418bcb81fbe98a9ab67452147c4dc6/NET%20Core/TestServer/Program.cs#L64

Then some nodes are created and linked to Items:
https://github.com/nauful/LibUA/blob/7e1445072a418bcb81fbe98a9ab67452147c4dc6/NET%20Core/TestServer/Program.cs#L84

You can also create more folders and link them to Items the same way:
- In the parent folder references, add ReferenceNode(Organizes) for parent folder -> child folder.
- In the subfolder's references, you can optionally add add ReferenceNode(OrganizedBy) for child folder -> parent folder.
