### ISSUE TITLE
Error monitoring

### ISSUE THREAD

**Issue by franklupo** [nauful/LibUA#129]
Hi, 
i connect client to Siemens plc. 
When read the statuscode is null but value and timestamps are ok. 
When create monitoring receive status **BadEncodingLimits Exceeded**

what am I doing wrong?

Best regards

**Comment by nauful** [comment]
Hello,

Can you share a Wireshark capture with no security?

**Comment by franklupo** [comment]
i don't know how to do with Wireshark

**Comment by nauful** [comment]
https://help.salesforce.com/s/articleView?id=000385344&language=en_US&type=1

Otherwise you might be monitoring too many items in a single call. Try batches of a few items at once.

**Comment by franklupo** [comment]
[opcua.zip](https://github.com/nauful/LibUA/files/12180724/opcua.zip)

**Comment by franklupo** [comment]
Hi,
I don't know if it helps but with this library it works 
https://github.com/convertersystems/opc-ua-client

best regards

**Comment by nauful** [comment]
Looks like a `PublishResponse` is too large for the sender/receiver according to the initial configuration. I need to see a capture with no security, this connection is secured with encryption so I cannot read the messages.

**Comment by franklupo** [comment]
[opcua2.zip](https://github.com/nauful/LibUA/files/12184549/opcua2.zip)

**Comment by franklupo** [comment]
encryption where should I disable?

**Comment by nauful** [comment]
https://github.com/nauful/LibUA/blob/7e1445072a418bcb81fbe98a9ab67452147c4dc6/NET%20Core/TestClient/Program.cs#L120

Change `SignAndEncrypt` to `Sign`.

**Comment by franklupo** [comment]
```
var messageSecurityMode = MessageSecurityMode.None;
var securityPolicy = SecurityPolicy.None;
```

**Comment by franklupo** [comment]
i'm using the port 4841 and the wireshark is setting for 4840.
try now

[opcua3.zip](https://github.com/nauful/LibUA/files/12185418/opcua3.zip)

**Comment by franklupo** [comment]
Reopen issue please

**Comment by nauful** [comment]
I can try to assist you with library usage but I prefer to keep issues for problems with the library itself. Please try my suggestions above and let me know if that works.

**Comment by franklupo** [comment]
The problem is the parameter filter in **MonitoringParameters**,
if present response **Goof** is null return **BadEncodingLimitsExceeded**
IF presente the notification not work.

**Comment by nauful** [comment]
Thanks, will note that if I see this issue again.
