### ISSUE TITLE
Can not write value to my variable

### ISSUE THREAD

**Issue by petruh1n** [nauful/LibUA#134]
Good afternoon!
I started your server and added my variable to the tree.
![102939](https://github.com/nauful/LibUA/assets/68856558/0b4e746e-5771-411a-ba37-ba8b7379410f)

I connect to the server using a third-party client (Prosys client).
I get an error when recording.
![103059](https://github.com/nauful/LibUA/assets/68856558/31383d9f-20c5-4642-88b3-7d9906b92d8a)

Please tell me what I'm doing wrong?

**Comment by nauful** [comment]
Hello,

Nodes on the server are not writable by default. If you want to write to a node, you must handle storing that value for later reads.

Implement this virtual method in your `Application`:
https://github.com/nauful/LibUA/blob/837d0072a338e690d1c30ec32649499ae12ee10c/NET%20Core/LibUA/Application.cs#L474C4-L474C88
The default implementation returns `BadNotWritable` for write attempts. If your node is writable, you can store the new value (to return on reads, possibly also store in a historical time series) and return `Good` for that node. If your node isn't writable, you can return `BadNotWritable`.

`WriteValue` is determined here:
https://github.com/nauful/LibUA/blob/837d0072a338e690d1c30ec32649499ae12ee10c/NET%20Core/LibUA/Types.cs#L5876
This includes `NodeId` and `Value`.

**Comment by nauful** [comment]
To return the written value when a node is read, look at this:
https://github.com/nauful/LibUA/blob/837d0072a338e690d1c30ec32649499ae12ee10c/NET%20Core/TestServer/Program.cs#L276

And this is to handle historical reads:
https://github.com/nauful/LibUA/blob/837d0072a338e690d1c30ec32649499ae12ee10c/NET%20Core/TestServer/Program.cs#L305

**Comment by petruh1n** [comment]
I return Good in the HandleWriteRequest method, the error no longer appears, but the value is still not displayed. 
I didn't quite understand what it means to store the new value. 
Could you share some example, please?

**Comment by petruh1n** [comment]
I managed to write down the value in this way. Is this the right decision?
![093034](https://github.com/nauful/LibUA/assets/68856558/6feefcb1-2dd5-4e75-80c0-6e74a7fc46ad)

**Comment by nauful** [comment]
Look at this sample code:
```
			private Dictionary<NodeId, DataValue> writtenValues = new Dictionary<NodeId, DataValue>();

			public override uint[] HandleWriteRequest(object session, WriteValue[] writeValues)
			{
				var respStatus = new UInt32[writeValues.Length];
				for (int i = 0; i < writeValues.Length; i++)
				{
					if (writeValues[i].AttributeId == NodeAttribute.Value)
					{
						writtenValues[writeValues[i].NodeId] = writeValues[i].Value;
						MonitorNotifyDataChange(writeValues[i].NodeId, writeValues[i].Value);
						respStatus[i] = (UInt32)StatusCode.Good;
					}
					else
					{
						respStatus[i] = (UInt32)StatusCode.BadNodeAttributesInvalid;
					}
				}

				return respStatus;
			}

			protected override DataValue HandleReadRequestInternal(NodeId id)
			{
				if (writtenValues.TryGetValue(id, out DataValue value))
				{
					return value;
				}

				Node node = null;
				if (id.NamespaceIndex == 2 &&
					AddressSpaceTable.TryGetValue(id, out node))
				{
					if (node == Node1D)
					{
						return new DataValue(new float[] { 1.0f, 2.0f, 3.0f }, StatusCode.Good, DateTime.Now);
					}
					else if (node == Node2D)
					{
						return new DataValue(new float[2, 2]
						{
							{ 1.0f, 2.0f },
							{ 3.0f, 4.0f }
						}, StatusCode.Good, DateTime.Now);
					}
					else
					{
						return new DataValue(3.14159265, StatusCode.Good, DateTime.Now);
					}
				}

				return base.HandleReadRequestInternal(id);
			}
```
			
You need to store the written value somewhere, publish data change, then return it on read.

**Comment by petruh1n** [comment]
Thank you very much.
Why do I need to return a value in HandleReadRequestInternal?

**Comment by nauful** [comment]
For read internal, you need to return the value of the node involved. This is the sent back to the client.
