### ISSUE TITLE
UaClient error to read a matrix

### ISSUE THREAD

**Issue by VitorKawao** [nauful/LibUA#139]
Hello Nauful,

I am having some problems when I try to read a matrix (array with two dimensions).
With an array with 1 dimension, it works perfectly

I am using your api to connect to KepServer.
I create there a matrix 3x3

![image](https://github.com/nauful/LibUA/assets/41079533/17bd24ef-0cef-4e3b-87d8-0a2aaed9c855)

Using Kepware Click Client, it can read correctly: [0;0;0][0;0;0][0;0;0]

![image](https://github.com/nauful/LibUA/assets/41079533/8a3ac93f-e1e5-4894-a029-97b4bb7e3fbd)

When I try to read with you api, it returns an ushort[9], but with a invalid 2

![image](https://github.com/nauful/LibUA/assets/41079533/4492b4b5-fcf2-49c4-8c18-9e71b07fc5c9)

But if I change the values of the matrix, it returns null

![image](https://github.com/nauful/LibUA/assets/41079533/ba9b5cf5-e347-4b01-8a74-d1f46d825ad9)
![image](https://github.com/nauful/LibUA/assets/41079533/fb4c65d6-5d3e-476e-ac58-e01fbbb5fe82)

Am I doing something wrong?

Thank you,
Vítor Guedes

**Comment by nauful** [comment]
Hello Vitor!

Could you please rerun that test while capturing with Wireshark and security mode set to None? I wonder what data is coming back. I may be deserializing incorrectly, 2D matrix has been a rare case for testing. I can look at the Wireshark capture to see what was read.

Thanks,
Nauful

**Comment by VitorKawao** [comment]
I downloaded the latest version, but it still has the same errors

**Comment by nauful** [comment]
Hello Vitor,

Do you have this commit?
https://github.com/nauful/LibUA/commit/cef29f87ec0c2b2b44c8077b065390de97721897

I am able to reproduce the issue before but not after this change. Let me know if that still fails with the latest commit.

Thanks,
Nauful

**Comment by VitorKawao** [comment]
I am sorry, I think I haven't.
Now I have it, and it worked

![image](https://github.com/nauful/LibUA/assets/41079533/e7de006e-56f3-4e68-a3b7-7be4bcbc735e)

Thank you,
Vítor Guedes

**Comment by nauful** [comment]
Hello Vitor,

Glad it worked! Feel free to let me know if you come across anything else.

Happy holidays,
Nauful
