### ISSUE TITLE
Error DefaultAddressSpace

### ISSUE THREAD

**Issue by gmjn** [nauful/LibUA#141]
![image](https://github.com/nauful/LibUA/assets/37955837/4e778cf5-ecfc-4da9-8342-82ca21672376)

I think code in Application.cs line 87 should be changed from:
AddressSpaceTable[new NodeId(UAConst.BaseDataType)].References.Add(new ReferenceNode(new NodeId(UAConst.Organizes), new NodeId(UAConst.DataTypesFolder), false));
to:
AddressSpaceTable[new NodeId(UAConst.BaseDataType)].References.Add(new ReferenceNode(new NodeId(45), new NodeId(UAConst.DataTypesFolder), true));
(Should probably also have been moved to line 829, but it is possible that there is some auto generation that makes it difficult)

![image](https://github.com/nauful/LibUA/assets/37955837/91cda281-f1a0-4824-bb16-cd35a3213e2e)

UInteger should be under Number not under Integer

Thanks for a good OPC UA library

**Comment by nauful** [comment]
Glad you like the library.

This address space is automatically generated from the OPC UA specification. It looks like unsigned integer is a subtype of regular integers, so I will leave it there. I only see 3 root categories in the original definition: double, float and integer.
