### ISSUE TITLE
Nullreference Exception in Client Sample

### ISSUE THREAD

**Issue by onnoverschuuren** [nauful/LibUA#145]
Just downloaded the full solution, set client as Startup Project and run.
In line 91 of Clients.cs of the LibUA solution I get a System.NullReferenceException

config was null

![Image1](https://github.com/nauful/LibUA/assets/76474792/583c920e-5800-4ea0-b5e0-6be6f427c174)

VS2022

Call Stack:
TestClient.exe!TestClient.Program.Main(string[] args) Line 114
	at \LibUA-master\NET\TestClient\Program.cs(114)

**Comment by nauful** [comment]
Please check that TestServer is running in the background. I recommend using .NET Core instead of the old .NET as these have been deprecated and will be removed at some point.

Recommended workflow:
Start Net Core>TestServer
Start Net Core>TestClient.
