### ISSUE TITLE
LingerState: Unhandled Exception - Invalid Argument

### ISSUE THREAD

**Issue by Znow** [nauful/LibUA#146]
Hi there!

Thanks for providing a great library.

All though when using it, with a plain and simple local running OPC-UA simulator on 0.0.0.0:4840,
LingerState throws an exception. A quick fix is to comment this out, and then the stuff works.

![image](https://github.com/nauful/LibUA/assets/265719/3a57ec69-1a75-4b01-a35e-90a009beda71)

I can demonstrate that connecting to the simulator via a simplle GUI application works just fine:

![Screenshot 2024-02-28 at 11 14 21](https://github.com/nauful/LibUA/assets/265719/c00be0ff-f207-4595-b531-5393fc7097ec)

**Comment by nauful** [comment]
Glad that you like it!

After some testing, it looks like the use cases for TCP linger state no longer exist. I have removed that code.

This was necessary in the past where a client or server would send data and close the connection without waiting for acknowledgement, so the data would never be received. The protocol waits for acknowledgements by default, so this isn't an issue anymore.
