### ISSUE TITLE
Method calls are not executed

### ISSUE THREAD

**Issue by bjornfe** [nauful/LibUA#147]
Overriding `public override CallMethodResult HandleCallRequest(object session, CallMethodRequest request)` is not fired uppon method calls from Softing OPC UA Client. The result in OPC UA Client is success, so it seems that the NetDispatcher is somehow handling this method call "under the hood"

**Comment by bjornfe** [comment]
I Tried to copy the implementation of `DispatchMessage_CallRequest` in NetDispatcher from NET/LibUA into the Core library. This works fine.

**Comment by nauful** [comment]
Can you share a wireshark capture of traffic with security set to None? Or did copying the method fix your issue? I'll check.

**Comment by nauful** [comment]
My mistake, I see the issue. Fixed now, please try it.

**Comment by bjornfe** [comment]
Thank you. This fixes the issue :)

**Comment by nauful** [comment]
Great!
