### ISSUE TITLE
Regarding client connection issues

### ISSUE THREAD

**Issue by yongzhi0113** [nauful/LibUA#159]
When using opcua client, connect to a specific Opcua Server machine.
Calling OpenSecureChannel() will succeed.
But calling FindServers() and GetEndpoints() will fail. (BadEncodingLimitsExceeded)

When the same Opcua Server is connected via UaExpert, the following message will appear.
If we press the agree button, we can successfully connect to Opcua Server.
I guess this may be the problem. How can I troubleshoot this problem?

===========================================
GetEndpoints failed using the discov overy URL opc.tcp://MX6PLATFORM0001:4840/ returned from FindServers. Do you want to try the URL opc.tcp://192.168. 1.15:4840/ with the hostname used to call FindServers?

The hostname of the discovery URL used to call GetEndpoints (mx6platform0001) was replaced by the hostname used to call FindServers (192.168.1.15) Do you also want to replace the hostnames of the EndpointURLs with this hostname?

**Comment by nauful** [comment]
If you try to connect via hostname, you need to do this to resolve the IP and connect via IP: https://stackoverflow.com/questions/68636144/c-sharp-resolve-hostname-with-dns-to-ip-address/68646923#68646923

If that still doesn't work, record a Wireshark capture with security disabled of the case where the calls fail and I can take another look.

**Comment by nauful** [comment]
Can you record a Wireshark capture with security disabled? I can look at that. Otherwise I don't have enough information to find a problem.

**Comment by yongzhi0113** [comment]
Sorry, there is no way to provide Wireshark capture.
I will close this issue.
