### ISSUE TITLE
TIMEOUT: get Server Status

### ISSUE THREAD

**Issue by jvanlangen** [nauful/LibUA#167]
When using this library (.NET Framework 4.8) causes the clients giving a TIMEOUT on the get Server Status.

Any thoughts?

**Comment by nauful** [comment]
Can you try reading server status on the server using the TestServer project? That's currently working for me.

**Comment by bevanweiss** [comment]
@jvanlangen any update on this?
What version of the library are you using?
You might also need to show some Wireshark logs of the 'conversation' showing the TIMEOUT error, and some information around what your application logic is that's using the library...  are you sure you're calling base.HandleReadRequestInternal(NodeId id) if the node isn't one of your application nodes?

**Comment by jvanlangen** [comment]
A, I've found the issue. We override the `HandleReadRequestInternal` method but didn't call the `base.HandleReadRequestInternal`. It's fixed now..
