### ISSUE TITLE
The node value and datatype differs depending on monitoring or reading the node.

### ISSUE THREAD

**Issue by antroa** [nauful/LibUA#17]
The node "Items\Trend 000001" value and datatype is different if monitoring or reading it. If monitoring, the value and datatype is correct. When reading, a constant value of "3.14159265" is shown and the datatype is invalid. Tested with UAExpert-UAClient.

**Comment by nauful** [comment]
Fixed: https://github.com/nauful/LibUA/commit/4a2ee9a48438d8aceeca55840320a05c2cb440a6
