### ISSUE TITLE
Is uaserver diagnostics supported?

### ISSUE THREAD

**Issue by antroa** [nauful/LibUA#18]
In the demo server, i see "ServerDiagnostics" nodes. But in UAExpert's "Server Diagnostics View" no information is shown in "Server Information", "Session Diagnostics" and "Subscription Diagnostics".
Is uaserver diagnostics supported?

**Comment by nauful** [comment]
No, however you can handle the node read events if you want to support this. It's a relatively rare and low-priority feature that I haven't implemented.
