### ISSUE TITLE
EUInformation/ExtensionObjects - client cannot read node data

### ISSUE THREAD

**Issue by pgrimmert** [nauful/LibUA#183]
Hello, 

first, thank you for creating such a library. 
I am having actually a hard time returning any data structure which is an ExtensionObject. I tried to utizlize already implemented structures like EUInformation, but even this structure cannot read by the client. I assume its related to the client readiny the particular datatype, provided with TypeId property.

I am using UAExpert and when i click the node variable on my object, the extension object encoding looks alright:
The body contains actual bytes. And nesting the objects inside extensinoobjects does also look alright on wireshark captures.

![image](https://github.com/user-attachments/assets/fd12ef73-af07-49c2-93bb-0ea849cc117f)
bytes look alright:
![image](https://github.com/user-attachments/assets/5e56f4bc-7c6b-4cfd-b92d-51b396d859e0)

I set the datavalue for variablenodes with type EUInformation like this:
![image](https://github.com/user-attachments/assets/6bf14102-d301-4897-91a8-39df3154f481)

UAExpert wont show any data for the selected node and is just plotting the following error in the log:
![image](https://github.com/user-attachments/assets/9a8290f4-6409-46d7-a036-06da16e372b4)

I am not sure if i have to reimplement the DataTypeDefinition for the Structure types which i require.
e.g. the EUInformation does not show a StructureDefinition etc (i know its not implemented yet). But i wonder how these complex structures are supposed to be read by the client software?

Also the same issue affects the basic server objects, in particular the "ServerStatus" node (i=2256). How am i supposed to set these structures? I have recently moved from opcua foundations stack and wanted to get my server working with your library. 

Here a sample how such structures do look like in the opcua foundation stack:
![image](https://github.com/user-attachments/assets/0141cf92-c0ef-4efc-8bd4-2ff5893fca67)

Any help would be appreciated.

**Comment by nauful** [comment]
Hello,

I'm glad that you've found my library useful.

I didn't implement many complex types, but to implement this you can add additional types in `Types.cs` and serialization in `MemoryBufferExtensions.cs`. This applies for any object that doesn't fit in an `ExtensionObject`.

Using `ObjectAttributes` as an example, here is the definition: 
https://github.com/nauful/LibUA/blob/3756283ad8d751ae3e6600d4078ff3f89b1fefbd/NET%20Core/LibUA/Types.cs#L7089
Here is the serialization and deserialization code:
https://github.com/nauful/LibUA/blob/3756283ad8d751ae3e6600d4078ff3f89b1fefbd/NET%20Core/LibUA/MemoryBufferExtensions.cs#L89

Most objects should only be a few fields with Encode + Decode methods.
