### ISSUE TITLE
Question on how to read data from PLC

### ISSUE THREAD

**Issue by jlanzarotta** [nauful/LibUA#184]
Hello,

I am totally new to OPCUA and the technology.  Is there a way to use your library to connect to an actual PLC and read data from it?

Thanks.

**Comment by nauful** [comment]
Yes, if your PLC can connect over TCP/IP as a server. Look at TestClient as a sample client for this library.

**Comment by jlanzarotta** [comment]
Many thanks.  I will check that out.
