### ISSUE TITLE
Call with BadTypeMismatch

### ISSUE THREAD

**Issue by VitorKawao** [nauful/LibUA#186]
Hello Nauful,

My client asked me to implement call/methods.
As I don't have his opc server, I tried to find one for free. So I found Prosys (https://prosysopc.com/products/opc-ua-simulation-server/)
I could Read its InputArguments and OutputArguments, but when I try the call, its execute the method at the server

![image](https://github.com/user-attachments/assets/22b012c2-5c84-4753-a9d3-f8a023201622)

But the StatusCode returns BadTypeMismatch

![image](https://github.com/user-attachments/assets/bf2f1ae9-64c3-4b36-8cd4-e274f35d4a12)

![image](https://github.com/user-attachments/assets/b29b9b7e-4aff-4cda-8587-9a504c52160d)

Do you know what can be?

Best Regards,
Vítor Guedes

**Comment by nauful** [comment]
Hello Vitor,

The server returns that error, not the client. Is the server able to read all of the input arguments passed? Would you be able to get an unsecured wireshark capture?

Regards,
Nauful

**Comment by VitorKawao** [comment]
Hello,

I think the server received the arguments, at least the "pow" and 15.0 and  executed correctly the method
![image](https://github.com/user-attachments/assets/4dff5fba-ed60-4201-877f-2ec1493b7d30)

I attached the wireshark zipped.
[call_wireshark.zip](https://github.com/user-attachments/files/17081053/call_wireshark.zip)

Thank you,
Vítor Guedes

**Comment by nauful** [comment]
There might be an issue with the return type but I can't find it in the wireshark capture. Can you trim the wireshark to only that part of the timeline, or tell me which ports are used for opcua?

Regards,
Nauful

**Comment by VitorKawao** [comment]
Hello,
I don't know if I understand correctly what to do with trim the wireshark. 
But it this one:

![image](https://github.com/user-attachments/assets/4c521afc-0d49-447e-9719-a256001388f8)

I attached another zip with the new wireshark, and I included a wireshark with uaexpert (it works with it, I don't know if it helps)

I am using 53530 port.
[wireshark.zip](https://github.com/user-attachments/files/17147751/wireshark.zip)

Best Regards,
Vítor Guedes

**Comment by nauful** [comment]
I see the UA traffic in `call_uaexpert` but not in `call_api`. Can you show me the body for call request and response via api?

This is the one for `call_uaexpert`:
![image](https://github.com/user-attachments/assets/4b6dff21-8889-4b69-ab9b-08424a1a71b0)

![image](https://github.com/user-attachments/assets/6a731d93-1e47-4567-ba99-7a47b6425030)

**Comment by VitorKawao** [comment]
Hello,

The call request
![image](https://github.com/user-attachments/assets/eed439fb-8281-4f32-96c0-6555b74febbd)

The call response
![image](https://github.com/user-attachments/assets/ca557cc2-f38c-4fcf-b4ae-8fbacce2a122)

I zipped again the wireshark
[call_api.zip](https://github.com/user-attachments/files/17188658/call_api.zip)

Maybe I am doing something wrong at the code.
![image](https://github.com/user-attachments/assets/bef16be0-0d0b-4b7c-84a0-56ab92af3627)


Best Regards,
Vítor Guedes

**Comment by nauful** [comment]
Found and fixed a bug, please try with the latest.

**Comment by VitorKawao** [comment]
Hello,

The BadTypeMismatch error was fixed, but unfortunately I have another problem. Now it is returning BadDecodingError

![image](https://github.com/user-attachments/assets/1087b26c-284d-4bef-9774-10dda2cafec8)

The problem seems to be at numOutputs

![image](https://github.com/user-attachments/assets/1f8cc414-fd60-4b66-a139-e984f659d150)

Because it only have two and succeeded became false

![image](https://github.com/user-attachments/assets/1c9f2a51-b7e7-4dfd-b2e9-91e998f71315)

I attached again the wireshark
[call_api.zip](https://github.com/user-attachments/files/17204023/call_api.zip)


Best regards,
Vítor Guedes

**Comment by nauful** [comment]
Hmm, pushed another update. Please try that and let me know if it works.

Thanks,
Nauful

**Comment by VitorKawao** [comment]
Now it is working!!

Thank you so much
Vítor Guedes

**Comment by nauful** [comment]
Great! I'll push a new package in a bit.

Thanks,
Nauful
