### ISSUE TITLE
.NET version does not send CloseSecureChannel

### ISSUE THREAD

**Issue by arj3090** [nauful/LibUA#187]
In .NET version (not CORE), when disconnecting, a CloseSecureChannel packet is not sent.

I believe the Disconnect method in client.cs is missing this:

               if (config.SessionIdToken != null)
               {
                   CloseSession();
               }
               if (config.ChannelID > 0)
               {
                   CloseSecureChannel();
               }

**Comment by nauful** [comment]
The server should handle this as a terminated connection. This doesn't break anything in the library and backporting those two methods will take more effort.
