### ISSUE TITLE
Server Certificate in Demo Server 

### ISSUE THREAD

**Issue by antroa** [nauful/LibUA#19]
The standard server certificate from libua demo server is missing some properties, e.g.:

X509v3 Basic Constraints, X509v3 Key Usage, X509v3 Extended Key Usage, X509v3 Subject Alternative Name.

I added a more conform DER encoded certificate (marked as usable for uaclient and uaserver, but uaserver should better a certificate marked as usable for server and uaclients should better use a certificate marked as usable for clients) and a certificate template for the XCA tool.

[lubua-clntsrvcert.zip](https://github.com/nauful/LibUA/files/4586442/lubua-clntsrvcert.zip)

**Comment by nauful** [comment]
The demo server certificate is a sample one generated via C#.

Thanks, adding to the readme.
