### ISSUE TITLE
If opc server not reachable, unhandled exception thrown, after long run, causing applicaiton exit abnormally, possibly due to thread competiting on socket.

### ISSUE THREAD

**Issue by xiaoyuvax** [nauful/LibUA#190]
UAClient Connection using sample code, retry loop forever if not connected, if opc server not reachable, after a long run, applicaiton exit abnormally, despite the entire code is enclosed in a try catch block.
AppDomain.CurrentDomain.UnhandledException finally caught the exception with immediate application exit. 
wrote some stacktrace in this exception handler shows:

Exception: An existing connection was forcibly closed by the remote host.

Stacktrace (line no seems not match the source):
> /CurrentDomain_UnhandledException at offset 222 in file:line:column <filename unknown>:0:0
> /UpdateStatusAfterSocketErrorAndThrowException at offset 119 in file:line:column <filename unknown>:0:0
> /CloseConnection at offset 182 in file:line:column <filename unknown>:0:0
> /ThreadTarget at offset 323 in file:line:column <filename unknown>:0:0

check in source, i guess:
```
private void ThreadTarget()
{
...
CloseConnection();   // -> this method call may cause Unhandled Thread Exception, possibly due to thead competiting on socket resources.
}
```

**Comment by xiaoyuvax** [comment]
possibly client.Connect()  is not threadsafe, as is what causes my problem.

**Comment by bevanweiss** [comment]
What version of the library are you using? (and .NET Core / .NET Framework?)
This should be something like 1.0.2X

Ideally you'd also provide a minimal reproducible repository for this issue.

**Comment by nauful** [comment]
This looks like a `SocketException` and should be fixed as of https://github.com/nauful/LibUA/commit/8051a828957317357b4a48b3c3b7de9fe28442fa in 1.0.28.

**Comment by xiaoyuvax** [comment]
i used 1.0.24,
upgrade to 1.0.28, solved!
thx!
