### ISSUE TITLE
Unable to publish TestServer as Windows Service

### ISSUE THREAD

**Issue by RafaelxFernandes** [nauful/LibUA#193]
I am trying to use your library to deploy the project TestServer as a Windows service, but I am encountering an error during the process. 
These are the publishing parameters (Profile settings) on Visual Studio 2022, using Windows 10:

![image](https://github.com/user-attachments/assets/906d1afc-cf2d-4eb2-b4f0-cf6988026aa0)

Running PowerShell as admin:

``` powershell
sc.exe create OPC.UA.LibUA binpath= C:\temp\LibUA\TestServer.exe start=auto
```

Service is created just fine:

![image](https://github.com/user-attachments/assets/9d08fa5d-09cb-4ebb-b5cf-0cc92ad6382e)

Clicking on `Start`:

![image](https://github.com/user-attachments/assets/c65619ee-c92f-4e25-80a3-d447cce36cbf)

Checking Event Viewer:

![image](https://github.com/user-attachments/assets/036ffaa3-d3d8-454a-995c-969f6edec4e3)

**Note:** I had to modify the function `TestServer` on `TestServer project > Program.cs` because the line `Console.ReadKey();` was breaking

``` csharp
private static void TestServer()
{
    var sw = new Stopwatch();
    sw.Start();

    var app = new DemoApplication();
    using ILoggerFactory factory = LoggerFactory.Create(builder => builder.AddConsole());
    var logger = factory.CreateLogger(nameof(TestServer));
    var server = new LibUA.Server.Master(app, 7718, 10, 30, 100, logger);
    server.Start();

    sw.Stop();
    logger.Log(LogLevel.Information, "Created and started server in {elapsedTime:N3} ms", sw.ElapsedMilliseconds);
    logger.Log(LogLevel.Information, "{protocol}://{listenAddress}:{listenPort}", "opc.tcp", "localhost", 7718);

    var timer = new System.Timers.Timer(1000);
    timer.Elapsed += (sender, e) => { app.PlayRow(); };

    timer.Start();
    //Console.ReadKey();
    Task.Delay(Timeout.Infinite).Wait();
    timer.Stop();

    server.Stop();
}
```

![image](https://github.com/user-attachments/assets/ff3e029d-9aba-45f1-9509-e1a016ee2704)

**Comment by nauful** [comment]
TestServer is a console app sample. It's not meant to be used as a service.

Look at https://learn.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer
Some important sections include setting service status and event logging.
