### ISSUE TITLE
BadSecureChannelTokenUnknown error in client resulting in crash

### ISSUE THREAD

**Issue by schmelnik** [nauful/LibUA#195]
Steps to reproduce:
- Start TestServer
- Start TestClient
- Wait

After some time the client crashes caused by the "tcp" member is being null in "OpenSecureChannelInternal"

You can make this problem more likely to happen by reducing the "reqLifetime" (same method) to much lower values (e.g. 3 seconds)

This is caused by the method "UnsecureSymmetric" returning "BadSecureChannelTokenUnknown" called by the "Consume" method  called by the "ThreadTarget" method.

Probably some locking is required to avoid normal communication while renewing the secure channel?

**Comment by nauful** [comment]
Fixed in https://github.com/nauful/LibUA/commit/732cac1736a96b7fb14474150495a05923f407a4 and published a new nuget package. Channel renewals were reading part of the next message and failing to decrypt.
