### ISSUE TITLE
Code is not disposing certain object instances

### ISSUE THREAD

**Issue by schmelnik** [nauful/LibUA#196]
According to Microsoft instances of the following typed should be disposed, or closed_
- ManualResetEvent
- Semaphore

There are several locations where instances of these types are being created but I do not see any "Close" or "Dispose"

Similar issue with the using of "MemoryBuffer" instances - I see at least 2 two instances where Dispose is not called, although it looks like in these cases there is no need to dispose (but this is is handled in the dispose method anyway)

**Comment by nauful** [comment]
Added to my TODO list for later. At the moment I only have time to fix breaking issues. I would likely use an object pool for these objects since most manual reset events are created by a calling method and signaled in the TCP receiver thread.
