### ISSUE TITLE
 Status code = 0X80020000

### ISSUE THREAD

**Issue by nurgaleevarman** [nauful/LibUA#198]
I have a LibUA OPC server running.
UA Expert connects fine, but another client sometimes can't connect to the server. It gives an error **"Sent TL error 0x80020000"**
Security set to None.

OPC UA Server has 10k variables. 

How i can fix it?

**Comment by nauful** [comment]
Can you please record a failed connection attempt with Wireshark and share the dump?

**Comment by nurgaleevarman** [comment]
[tl error.pcapng.gz](https://github.com/user-attachments/files/18246208/tl.error.pcapng.gz)

line 3787, 7584, 11476

**Comment by nauful** [comment]
![image](https://github.com/user-attachments/assets/90c997f1-abe7-4a1e-844e-2d0273ac81a3)
Your read request is too large. Try reading 1k-10k nodes at a time. UAExpert reads in batches.

**Comment by nurgaleevarman** [comment]
Thank you!
Temporary solution is to increase the buffer.
`server = new LibUA.Server.Master(opcUA, port, 10, 30, 100, logger, **536870912**);`

**Comment by nauful** [comment]
I would recommend using a smaller buffer as you will get unpredictable memory spikes from clients connecting, and potentially many performance issues.

**Comment by nurgaleevarman** [comment]
Hello! This error is sent by the LibUA OPC server.
OPC UA Server uses over 10,000 tags with string identifiers.

**Comment by nauful** [comment]
Use batches instead of very large single calls. This is unsupported behavior.
