### ISSUE TITLE
Invalid Security Certificate

### ISSUE THREAD

**Issue by YW767486516** [nauful/LibUA#2]
![image](https://user-images.githubusercontent.com/45729918/65828813-ac673d00-e2d1-11e9-8d89-86fdff74013b.png)

Hi,
There is a problem after installing the certificate

**Comment by nauful** [comment]
Hello,

My default test certificate is a sample self-signed certificate for testing OPC UA with secured communication and for certificate-based login. It is not designed to be used as a general purpose trusted certificate. For that, you will likely need to purchase a signature from a trusted authority.

Regards,
Nauful
