### ISSUE TITLE
UaExpert Error: Number of acknowledgement results (0) does not match number of acknowledgements(1)

### ISSUE THREAD

**Issue by davidguidali** [nauful/LibUA#27]
Hi 
Thank you very much for your client / server implementations, I like them a lot!
I am actually learning OPC-UA, so this may be a basic question. I tried your server and connected with UA Expert (v1.5.1.331). Everything seems to work fine, however I get this error a lot in the logs:

Error: Number of acknowledgement results (0) does not match number of acknowledgements(1)

![image](https://user-images.githubusercontent.com/61904428/87118381-85d02c80-c27b-11ea-8b2f-718d63c90e4f.png)

Do you know whats the issue there?

**Comment by mweissi** [comment]
I also observe this messages with UaExpert

**Comment by nauful** [comment]
Could you please upload an installer for your version of UaExpert?

I suspect behaviour is different from the previous version(s) now:
![image](https://user-images.githubusercontent.com/50109829/87154780-6d621100-c27f-11ea-9bd5-63e4919a1046.png)

**Comment by davidguidali** [comment]
Thats the client I'm using, downloaded from unified automation page https://www.unified-automation.com/de/downloads/opc-ua-clients/file/download/details/uaexpert-v144.html

[uaexpert-bin-win32-x86-vs2008sp1-v1.5.1-331.zip](https://github.com/nauful/LibUA/files/4904342/uaexpert-bin-win32-x86-vs2008sp1-v1.5.1-331.zip)

**Comment by nauful** [comment]
Done, added support for subscription acknowledgements and publishing available sequence numbers.

Note that subscription acknowledgements are asynchronous, so you might still see a harmless warning (e.g. sent 0 or 2 when 1 is consistently returned from the server). Available sequence numbers only cover the current published data change or event notification.

**Comment by davidguidali** [comment]
Cool, thanks very much! :)
