### ISSUE TITLE
OPC-UA Server Session

### ISSUE THREAD

**Issue by maveyx** [nauful/LibUA#28]
Hi nauful,

Thank you very much for your OPC-UA implementation!
I'm currently testing your test server implementation and saw that the following method, which is related to the session, is not implemented yet:

```
public override object SessionCreate(SessionCreationInfo sessionInfo)
{
     // Create and return a session object with sessionInfo

    return null;
}
```

Can you give me any advice on what object has to be created and returned in SessionCreate() and how to respond this to a client? 
Is there already a predefined type available?

Thank you very much in advance!

**Comment by nauful** [comment]
Hello,

Glad to see that this project is useful to others.

This is completely optional, I have updated the source to reflect that. The test server project is a fully functional stand-alone server as-is.

When a client connects, you can see their endpoint information in sessionInfo and optionally return your own custom object. That same object you return (or null) is passed as a parameter when the session is validated (as anonymous, username + password or certificate) with a few parameters that a UA client may optionally use for authentication/identification. For example, you may choose to have certain nodes visible/hidden from users with different usernames depending on your application. This is why most of the methods, especially those involving the UA address space, also pass in the session object as a parameter. You can update the session object in any method, especially useful to do so in the session activation method.

In the most common case where you don't need to track individual clients and handle them differently, you can safely ignore the session object.
