### ISSUE TITLE
Bug in saving certificate and private key

### ISSUE THREAD

**Issue by jskala** [nauful/LibUA#3]
Hello,

I think I found a bug in LibUA.UASecurity. When you use MemoryStream.GetBuffer(), it may contain nulls at the end. It should be MemoryStream.ToArray() instead.

I needed a 2048 b long key and the exported .pem file had null characters at the end. It caused trouble when importing the file later, Base64 decoding didn't work.

Best regards
Jiri

**Comment by nauful** [comment]
Thanks, I have fixed this now. If any problems remain, please feel free to reopen the issue or submit a pull request with a fix.

Regards,
Nauful
