### ISSUE TITLE
Exception during call CreateSession

### ISSUE THREAD

**Issue by paolotraversi** [nauful/LibUA#35]
Hello, this is the first time I am using this library.
I wrote a test program to connect to an OPC UA server located on a remote VPN server. The server is accessible without any type of encryption or username / password.
The library goes into exception during the call to the CreateSession, in the DECODE function as the byte ENCODINGMASK is not recognized.
This is the part of the code:

      var appDesc = new ApplicationDescription("urn:Demo","uri:Demo",new LocalizedText("UA client"),ApplicationType.Client,null,null,null);

      // Create new client object to reset previous secure channel settings
      var client = new Client("172.16.34.215", 4841, 1000);
      var connectRes = client.Connect();
      if (connectRes != StatusCode.Good)
      {
        Console.WriteLine($"OPC Connect error: {connectRes}");
        Environment.Exit(1);
      }

      var openRes = client.OpenSecureChannel(MessageSecurityMode.None, SecurityPolicy.None, null);
      if (openRes != StatusCode.Good)
      {
        Console.WriteLine($"OPC OpenSecureChannel error: {openRes}");
        Environment.Exit(1);
      }

      var createRes = client.CreateSession(appDesc, "urn:Demo", 120);
      if (createRes != StatusCode.Good)
      {
        Console.WriteLine($"OPC CreateSession error: {createRes}");
        Environment.Exit(1);
      }

      var activateRes = client.ActivateSession(new UserIdentityAnonymousToken("0"), new[] { "en" });
      if (activateRes != StatusCode.Good)
      {
        Console.WriteLine($"OPC ActivateSession error: {activateRes}");
        Environment.Exit(1);
      }

Can I have some ideas?

Thanks,
Paolo

**Comment by nauful** [comment]
Could you please upload a Wireshark capture of network traffic?

**Comment by paolotraversi** [comment]
Hello nauful this is a capture of network traffic. The IP Address is 172.16.34.215 (OPC SERVER) on port 4841
Thank you for help
![Cattura](https://user-images.githubusercontent.com/72490013/95431428-6f567180-094d-11eb-83f9-fe05f902fa53.PNG)

**Comment by nauful** [comment]
Could you please upload the capture file so I can take a look?

**Comment by paolotraversi** [comment]
Of course. I attach a zip file.
If you extract file there is "Test.pcapng" make from Wireshark.

Thanks alot for your help
[Test.zip](https://github.com/nauful/LibUA/files/5347662/Test.zip)

**Comment by nauful** [comment]
Looks like SessionId is encoded as a GUID, this is a rare case. Most servers don't use GUID types for session ids. I'll try to add support to encode/decode NodeId as GUID type.

Would it be possible to use your server for testing?

**Comment by paolotraversi** [comment]
Hello Nauful, unfortunately the OPC server (is a food device for meat cutting) is installed by a customer only reachable in VPN with authentication in two steps by email so it is not reachable.
Anyway, if you agree, I can test the modifications for you.
The times will lengthen, unfortunately I think it’s the only way to do that, if you’re willing to test the changes this way.
thanks a lot for all the support

**Comment by nauful** [comment]
I will try to add support for encoding/decoding GUID NodeIds, will get back to you in a bit.

**Comment by paolotraversi** [comment]
The device will be turned off during the weekend. I will be able to test the change from Monday.
Thank you very much for all

**Comment by nauful** [comment]
Made a quick fix (fixed length 16 byte strings for the case of GUIDs), please let me know if it works.

**Comment by paolotraversi** [comment]
Hello Nauful,
i try the fix and now the library doesen't go into exception, but i can't read the configuration node. I attach a zip file, with two images and the Wireshark dump.
In the first image you see the debug application, and in the second the remote OPC UA Server with the node.
I wrong the nodeId configuration or ReadValueId configuration?

Now the customer switch off device, i continue the test monday morning.

Thanks alot and have a nice weekend.
[test.zip](https://github.com/nauful/LibUA/files/5355756/test.zip)

**Comment by nauful** [comment]
Looks like the requested encoding in your code is invalid for that server (RealValueId configuration). For DataEncoding, QualifiedName(0, null) instead of QualifiedName(2, null) should work in most cases. Could you also upload a Wireshark capture of UaExpert while reading that node?

![image](https://user-images.githubusercontent.com/50109829/95697280-d1400100-0c03-11eb-826b-1b91492ba828.png)

**Comment by paolotraversi** [comment]
[dump_UAExpert.zip](https://github.com/nauful/LibUA/files/5363554/dump_UAExpert.zip)

I attach a wireshark dump when UAExpert make a read request.
I try to change a QualifiedName(0, null) to QualifiedName(2, null), but the result is the same, i can't read anything.

**Comment by nauful** [comment]
I think you might have uploaded an incorrect capture, this one doesn't contain any opcua traffic. The previous two did.

**Comment by paolotraversi** [comment]
Sorry, I try to create the dump asap

**Comment by paolotraversi** [comment]
[dump_uaexpert_1.zip](https://github.com/nauful/LibUA/files/5365259/dump_uaexpert_1.zip)

Ok now the dump is correct.

**Comment by nauful** [comment]
Made a quick change to the source, please update and try again with QualifiedName(0, null).

**Comment by paolotraversi** [comment]
![image](https://user-images.githubusercontent.com/72490013/95756996-d30ed080-0ca6-11eb-9c82-74f952fdd51d.png)
[dump_write_UaExpert.zip](https://github.com/nauful/LibUA/files/5365671/dump_write_UaExpert.zip)
Hello Nauful,
now i can read the nodes with QualifiedName(0, null)!!!

The last problem now i can't write a parameter.
The function "Write" return "good", but at the next read the value not changed.
I Attack a picture with the part of code and the dump of UaExpert while it write a parameter.

Thanks alot for all

**Comment by nauful** [comment]
I think this server accepts a call request as a program, not direct write requests:
![image](https://user-images.githubusercontent.com/50109829/95760037-287bbb00-0c70-11eb-90a3-ad0010a84762.png)

I don't have any samples off-hand, but there should be a call request method on the client API.

**Comment by paolotraversi** [comment]
Ok, i'll search the method in client API.

Thanks you for all and for your patiente

**Comment by paolotraversi** [comment]
![image](https://user-images.githubusercontent.com/72490013/95764159-5d0f6700-0cb0-11eb-8718-c4870be91678.png)

I find client API Method "Call", with a request call "sendProgram" and now i can write the program number in the device.
