### ISSUE TITLE
OPC Foundation Certification

### ISSUE THREAD

**Issue by Polyteres** [nauful/LibUA#44]
Hi Nauful, we would like to know if LibUA has the OPC Foundation Certification. We have found this possibility here:

https://opcfoundation.org/certification/how-to-certify/

Best Regards.

**Comment by nauful** [comment]
Hello,

No, this library is primarily in maintenance mode, so I only make changes to handle updates, fixes or workarounds as needed. I also accept pull requests if anyone else wants to work on the library. Other than that, I don't have any plans to work on OPC.
