### ISSUE TITLE
OPC Certification

### ISSUE THREAD

**Issue by Polyteres** [nauful/LibUA#45]
Hi, we have been talking in my company about the possibility of certifying the LibUA library through the OPCFoundation. If possible, we would like to contact you privately to discuss certain aspects of the process, as we understand that this site is not suitable as it is not a problem with LibUA. So, if you agree, tell us how to contact you directly.

Thanks for your time.

**Comment by nauful** [comment]
Hello,

Please email me: github username @gmail.
