### ISSUE TITLE
Cannot connect to SIMATIC WinCC UA

### ISSUE THREAD

**Issue by IvoFortunov** [nauful/LibUA#48]
Hello,
I continue exploring your library, and it looks very promissing.
The final goal of my project is to connect to SIMATIC WinCC. My application is a server. Everything works fine with clients like UAExpert and other, but when I try to connect from SIMATIC WinCC I've got the following:
1. With security set to none, SIMATIC sends  "CloseSecureChannelRequest"
Wireshark log: [SecurityNone.zip](https://github.com/nauful/LibUA/files/6219516/SecurityNone.zip)
2.With security Basic128Rsa15 and the certificate from ERRATA(with the original pem, maybe my mistake) i get BadInternalError
WIreshark log: 
[SecurityBasic128Rsa15.zip](https://github.com/nauful/LibUA/files/6219537/SecurityBasic128Rsa15.zip)

The Consume gives (-4), exception is: "Error occurred while decoding OAEP padding". Decoding problem, maybe because the private key is wrong, but I don't have a PEM file for the certificate from ERRATA. 

3.With security Basic128Rsa15 and the original certificate i get Unknown error, but things look better
WIreshark log: 
[SecurityBasic128Rsa15_org_cert.zip](https://github.com/nauful/LibUA/files/6220051/SecurityBasic128Rsa15_org_cert.zip)

Please help me solve this issue!
Thanks in advance

**Comment by nauful** [comment]
I can't easily find UA traffic in your dump, could you filter them to only include the ports used for UA traffic?

**Comment by IvoFortunov** [comment]
I think I've managed to filter them. If you write "opcua" in filter, they are filtered by protocol.

3. With security Basic128Rsa15 and the original certificate i get Unknown error, but things look better
WIreshark log:
[SecurityBasic128Rsa15_org_cer_opcua.zip](https://github.com/nauful/LibUA/files/6222784/SecurityBasic128Rsa15_org_cer_opcua.zip)

**Comment by nauful** [comment]
Seems to expect a specific structure for the read value of Server_ServerStatus_State.

Could you capture traffic from a server-client configuration that works, with None security mode? That same value blob can be reused here.

**Comment by IvoFortunov** [comment]
Here is working log with Unified Automation Test UA Server and last version of Simatic WinCC
Wireshark log:
[WorkingConnection_new_WinCC.zip](https://github.com/nauful/LibUA/files/6236850/WorkingConnection_new_WinCC.zip)

**Comment by IvoFortunov** [comment]
Ok I fixed the connection issues. WinCC asks for "ServerCapabilities_OperationLimits" so I've added them to "internalAddressSpaceValues". It also expects UInt32 as an answer.
Now i connects and browses "Server Node" but it doesn't wrowse "Items Node".
Can you please hel me with this issue.
Wireshark log:
[Connected_Cannot_Browse_Items.zip](https://github.com/nauful/LibUA/files/6241241/Connected_Cannot_Browse_Items.zip)

**Comment by nauful** [comment]
What is the value for MaxNodesPerBrowse? It seems to pick that as 0 and not browse.

**Comment by IvoFortunov** [comment]
No it is 100, and yet another strange thing - it seams to ask for NodeId(0,0) instead of (2,0) when I try to browse Items folder.
It looks like that WinCC thinks that Items have nodeId=0
![NodeId_0](https://user-images.githubusercontent.com/81407414/113308341-bdea3480-930e-11eb-9580-80f83a58bd38.PNG)

In the working configuration it seams to ask for the correct NodeId.

**Comment by nauful** [comment]
Could you make a pull request to merge your fixes into the main library?

From the root, there should be a link to ns=2;i=0 that represents items. It seems that the namespace is dropped? I'm not sure how to fix that.

**Comment by IvoFortunov** [comment]
I continue investigating, when I finish I will make a pull request with all the fixes.

**Comment by IvoFortunov** [comment]
It is very strange behaviour. When I've changed NodeId(2,0) for Items to NodeId(2,"Items") - string identifier WinCC started to browse the Items.

**Comment by nauful** [comment]
Is the browse link from root to items the same i.e. ns=2;i=0 and also updated similarly to ns=2;s="Items"?

I wouldn't use this change for other servers, many (especially embedded) don't allow string identifiers.

**Comment by IvoFortunov** [comment]
No this change is only for my project!
I've just changed ns=2;i=0 to ns=2;s="Items".
For now we only have to add ServerCapabilities_OperationLimits" (12 values) to "internalAddressSpaceValues".
Now I have other issues, and when I solve them we can decide together what to include in the library.

P.S. Can we communicate by email, when there are things to discuss?

**Comment by nauful** [comment]
You can email me: github username @gmail

**Comment by IvoFortunov** [comment]
It finally works:
![Working WinCC](https://user-images.githubusercontent.com/81407414/113480658-2ddaf500-949e-11eb-988f-06f315cbba87.PNG)
Thanks for the help!
