### ISSUE TITLE
Crash in .net core test apps

### ISSUE THREAD

**Issue by krgiddings** [nauful/LibUA#50]
I downloaded the repo and compiling everything, and ran the client and server test apps,  and they both raise exceptions.

**Comment by nauful** [comment]
What exceptions do you see? I just tried and they work for me.

**Comment by nauful** [comment]
I've reverted a bad addition to the server project, should be fine now. Nothing wrong with the client test app.

**Comment by krgiddings** [comment]
ok,  thanks,  I'll download and test tomorrow.
