### ISSUE TITLE
Bug fix ActivateSession password encryption.  

### ISSUE THREAD

**Issue by BangABit** [nauful/LibUA#53]
Thanks for the development of this library, this was very useful for the development of an OPC UA client to connect a S7-1500 PLC with MessageSecurityMode.None with username and password. 
Unfortunately there was one bug that took me some time to figure out why the ActivateSession call was not accepted by the server. 
Finally I found there was something wrong with the encryption of the password. 
After doing the change below the ActivateSession was accepted by the server.
I am not sure if this is affecting any other ActivateSession with different policies, but for me this is working. 
Maybe you can apply this change to the git library? 

LibUA/NET/LibUA/Client.cs
original:
```						
if (config.RemoteNonce != null)
{
    Array.Copy(config.RemoteNonce, 0, crypted, offset, config.RemoteNonce.Length);
    offset += config.RemoteNonce.Length;
}
Array.Copy(rndBytes, 0, crypted, offset, rndBytes.Length);
offset += rndBytes.Length;
```
After edit:
```						
if (config.RemoteNonce != null)
{
    Array.Copy(config.RemoteNonce, 0, crypted, offset, config.RemoteNonce.Length);
    offset += config.RemoteNonce.Length;
}
else
{
    Array.Copy(rndBytes, 0, crypted, offset, rndBytes.Length);
    offset += rndBytes.Length;
}
```

**Comment by nauful** [comment]
Thanks for figuring that out. Merged and updated source.
