### ISSUE TITLE
Error in project NET\LibUA

### ISSUE THREAD

**Issue by r-anders** [nauful/LibUA#56]
I've just got the following error(s):
CS0104	"RSACng" is an ambiguous reference between "LibUA.Security.Cryptography.RSACng" and "System.Security.Cryptography.RSACng".	LibUA	c:\@D\Dev\OPC-UA\LibUA-master\NET\LibUA\Security.cs	399
It relates to statement
`	var rsa = new RSACng();`  
in function  ImportRSAPrivateKey() and ImportRSAPublicKey().
Looking at the counterpart in NET Core, there is the statement
`	var rsa = new RSACryptoServiceProvider();`
By replacing the error causing lines with the corresponding lines from NET Core  the errors disappear.
I cannot decide whether the content of this change is correct.

Afterwards new errors in projects TestClient, Testserver appear, same reason.
It relates to statement
`	var certPrivateCNG = new RSACng(appCertificate.GetCngPrivateKey());`
The counterpart in NET Core seems to be on a complete other way.
So I replaced the error causing statement with 
`	var certPrivateCNG = new LibUA.Security.Cryptography.RSACng(appCertificate.GetCngPrivateKey());`
I cannot decide whether the content of this change is correct.
(This kind of change could also have been made in project LibUA)

ralf

**Comment by nauful** [comment]
I don't see this problem when building locally:

```1>------ Rebuild All started: Project: LibUA (NET Core\LibUA), Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: LibUA (NET\LibUA), Configuration: Debug Any CPU ------
2>  LibUA -> \LibUA\NET\LibUA\bin\Debug\LibUA.dll
3>------ Rebuild All started: Project: TestClient (NET\TestClient), Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: TestServer (NET\TestServer), Configuration: Debug Any CPU ------
1>LibUA -> \LibUA\NET Core\LibUA\bin\Debug\netstandard2.0\LibUA.dll
3>  TestClient -> \LibUA\NET\TestClient\bin\Debug\TestClient.exe
4>  TestServer -> \LibUA\NET\TestServer\bin\Debug\TestServer.exe
5>------ Rebuild All started: Project: TestServer (NET Core\TestServer), Configuration: Debug Any CPU ------
6>------ Rebuild All started: Project: TestClient (NET Core\TestClient), Configuration: Debug Any CPU ------
6>TestClient -> \LibUA\NET Core\TestClient\bin\Debug\netcoreapp3.1\TestClient.dll
5>TestServer -> \LibUA\NET Core\TestServer\bin\Debug\netcoreapp3.1\TestServer.dll
========== Rebuild All: 6 succeeded, 0 failed, 0 skipped ==========```

Old .NET was missing some crypto libraries that .NET Core has added, hence the difference between the two. Either way it's functionally equivalent (identical algorithms and behaviours), so should be fine with either of your changes.
