### ISSUE TITLE
NodeMethod Demo

### ISSUE THREAD

**Issue by vincentTea** [nauful/LibUA#57]
Your project is great, it helped me a lot, but I don’t understand NodeMethod
Can you provide the demo of nodemethod, thank you

**Comment by nauful** [comment]
NoteMethod defines client-readable address space, but does not affect server functionality:
https://reference.opcfoundation.org/v104/Core/docs/Part3/5.7/

You can add one to your address space in the same way you would for e.g. NodeVariable.
