### ISSUE TITLE
DataType of ExtensionObject stays null in UaExpert

### ISSUE THREAD

**Issue by Ttberg** [nauful/LibUA#62]
![DataTypeNull](https://user-images.githubusercontent.com/63335009/128178771-9fc4373b-fd09-44f5-aa9c-5b357b72ab9d.PNG)

When I read the server status of the OPCUA reference server using UaExpert, the datatype is correctly resolved. However, when I read the server status of the LibUA, the Datatype is Null (see image).

Do you have any idea why this happens?

**Comment by nauful** [comment]
I don't serialize extension object types because I couldn't find concrete information in the UA spec. If you capture those reads from the reference server with Wireshark I could take a look at it.
