### ISSUE TITLE
System.Exception on CreateSession

### ISSUE THREAD

**Issue by loliparra80** [nauful/LibUA#68]
I have a simple test console application from your samples:

`var appDesc = new ApplicationDescription(
				"urn:DemoApplication", "uri:DemoApplication", new LocalizedText("UA SDK client"),
				ApplicationType.Client, null, null, null);
ApplicationDescription[] appDescs = null;
EndpointDescription[] endpointDescs = null;

Client clientUA = new Client("127.0.0.1", 49320, 1000);
clientUA.Connect();
clientUA.OpenSecureChannel(MessageSecurityMode.None, SecurityPolicy.None, null);
clientUA.FindServers(out appDescs, new[] { "en" });
clientUA.GetEndpoints(out endpointDescs, new[] { "en" });
var createRes = clientUA.CreateSession(appDesc, "urn:DemoApplication", 120);
clientUA.Disconnect();
`

But when try to make de CreateSession I had an Exception:

![image](https://user-images.githubusercontent.com/19977368/130446391-a1a6ec63-94f5-4e8b-9120-cc41a29606dc.png)

This is the server configuration, I had configured without security.
![image](https://user-images.githubusercontent.com/19977368/130446608-880e6abd-b457-4f35-b46b-ec9725c134ac.png)

If I set the security with Basic256Sha256, then a get another error:

![image](https://user-images.githubusercontent.com/19977368/130447125-b2cf8e21-c283-4e3e-b1c3-1e3365b7e53c.png)

The code with security:

`		var usernamePolicyDesc = endpointDescs
			.First(e => e.UserIdentityTokens.Any(t => t.TokenType == UserTokenType.UserName))
			.UserIdentityTokens.First(t => t.TokenType == UserTokenType.UserName)
			.PolicyId;

		clientUA = new Client("127.0.0.1", 49320, 1000);
		var connectRes = clientUA.Connect();
		clientUA.OpenSecureChannel(MessageSecurityMode.SignAndEncrypt, SecurityPolicy.Basic256Sha256, serverCert);
`

Maybe you can understand better the error than me and suggest me another configuration o whatever.

Thank you.

**Comment by nauful** [comment]
Could you share the server with me so I can test this locally?

**Comment by loliparra80** [comment]
Hello, today I have tried my test application directly as a new project in your LibUA solution, with the LibUA reference directly from your LibUA project, and also ser the Token with "Anonymous" and now it's working.

var activateRes = client.ActivateSession(new UserIdentityAnonymousToken("Anonymous"), new[] { "en" });

Maybe the latest release in nuget package installer is not already updated, I don't know. Thank you.
