### ISSUE TITLE
How does the server change the label value

### ISSUE THREAD

**Issue by nihao-git** [nauful/LibUA#74]
Hello, How does the server change the label value，I've assigned permissions to each label, but I still can't write to the client.

**Comment by nauful** [comment]
I don't understand what label you are referring to. Could you show me a screenshot or code sample?

**Comment by nihao-git** [comment]
![1644543750(1)](https://user-images.githubusercontent.com/53027001/153525519-e0ed8282-4999-4ca9-9a24-766ce2b0f9d6.jpg)
Sorry, I checked yesterday, it should be called node in your code, the value of node cannot be written from the client side, I have added permission to the node in the server code, but it still cannot be written, is it my wrong to add permission, or should not be added in this way, please advise, thank you.

**Comment by nauful** [comment]
Server nodes don't accept UA writes by default. To do this, in your application (subclass of `LibUA.Server.Application`), you can implement this method:
`public virtual UInt32[] HandleWriteRequest(object session, WriteValue[] writeValues)`

You can match node ids according to `WriteValue.NodeId` and Value would be `WriteValue.AttributeId`. If you update the value of a node, remember to call `MonitorNotifyDataChange` to send a notification to all subscribers.

**Comment by nihao-git** [comment]
Thank you, problem solved.
