### ISSUE TITLE
Internal Addresses not update & Extension Objects

### ISSUE THREAD

**Issue by celsoprieto** [nauful/LibUA#75]
Why all internal addresses nodes are empty?

![image](https://user-images.githubusercontent.com/15360711/153746465-a8235637-5b53-458f-b0a6-60850ded3392.png)

Which is the best method to keep update internal addresses?

Could you help me to manage (ExtensionObject) ServerStatus?

**Comment by nauful** [comment]
The default address namespace uses autogenerated code based on the specification. I used values and relationships where defined, but many nodes have no default values.

Handling read requests is the best way. Also remember to publish a data changed notification when updating values.

I couldn't find a standard UA type for ServerStatus. If you can share a specification with me, I could show you how to use object encoding to generate that type on read.

**Comment by celsoprieto** [comment]
@nauful where could i send you a wireshark file?

**Comment by nauful** [comment]
You can drag and drop a wireshark file here to upload.

Try creating a MemoryBuffer, look at the Encode methods to add the fields one by one, then attach that to an ExtensionObject with type ServerStatus. You can use this in HandleRead to return the current server status, and publish once per second with the latest CurrentTime (data change notification)

**Comment by celsoprieto** [comment]
[Serverstatus.zip](https://github.com/nauful/LibUA/files/8077252/Serverstatus.zip)

**Comment by nauful** [comment]
If you use the Encode methods to write those fields into a MemoryBuffer and attach to an ExtensionObject with type ServerStatus, that creates the value for you.

You can return that value in HandleRead, and publish with data change notification.

I don't have any plans to add this to the core SDK, but the description above should provide what you want.

**Comment by nauful** [comment]
That should have solved your issue. Please leave a comment if you still have this problem.
