### ISSUE TITLE
About Democlient UserIdentityUsernameToken

### ISSUE THREAD

**Issue by DylanSu1216** [nauful/LibUA#82]
Hello I am learning OPC and LibUA library now.
I have some problems.
I use DemoClient to connect DemoServer,can work.
I try to use "UserIdentityUsernameToken" this method to connect Server.
I comment code "UserIdentityAnonymousToken" and ues"UserIdentityUsernameToken",like picture.
![螢幕擷取畫面 2022-06-01 151546](https://user-images.githubusercontent.com/106652618/171350718-e0b47044-26ae-40bf-86eb-218100e0d0c7.png)

But I get some Error like this.
![螢幕擷取畫面 2022-06-01 151217](https://user-images.githubusercontent.com/106652618/171351201-d1cadfec-e94f-422a-b595-c0ac2c130a91.png)

I want to know where am I doing wrong.

Thanks a lot.

**Comment by nauful** [comment]
Could you use Wireshark to capture traffic from the client to the server? I can take a look at the capture and tell you if there's an issue.

**Comment by DylanSu1216** [comment]
@nauful Thanks your help.
I change the Sourcecode NetDispatcher.cs line:883 like this
![image](https://user-images.githubusercontent.com/106652618/172098737-05510603-9fdd-4119-a4ae-8f51e88ebaae.png)
Matrikon method Basic256 worked.
![image](https://user-images.githubusercontent.com/106652618/172099137-ca67a455-18e7-4650-80b0-fa27d7119232.png)

But NetDispatcher.cs is in libUA.dll liarbry
If I reference dll is there another way for me to change this more easily?

**Comment by nauful** [comment]
This seems to be `Application.SessionValidateClientUser`. You can make a class that inherits from `Application` and just override that one method. Example from the DemoServer (uses `DemoApplication` which inherits from `Application`): https://github.com/nauful/LibUA/blob/7c9e1a22ba38743af4dbdd3bdb1420788e2238e6/NET%20Core/TestServer/Program.cs#L488

**Comment by DylanSu1216** [comment]
@nauful,Good evening. 
I can't understand. The `Application.SessionValidateClientUser` just use to check username& password,How to know client use what policy type of security(Basic256、Basic128Rsa15 or Basic256Sha256)

I mean the ` NetDispatcher.cs line:883` I need change enum of `SecurityPolicy` .
But ` NetDispatcher.cs` is in dll ,So my OPC server policy type is unchangeable?
![image](https://user-images.githubusercontent.com/106652618/172414167-55904505-1895-4d7d-9923-98ca4be02448.png)

Thanks your help.

**Comment by DylanSu1216** [comment]
@nauful Maybe I can do this right? 
![image](https://user-images.githubusercontent.com/106652618/172439264-ddb0e40e-db03-4b2b-8751-2bc9928e6460.png)

**Comment by nauful** [comment]
Implementing `SessionValidateClientUser` in your `Application` derived class will give you the username and password requested. 

If you modify `GetEndpointDescriptions` in your `Application` derived class, you can configure which security policies are enabled: https://github.com/nauful/LibUA/blob/7c9e1a22ba38743af4dbdd3bdb1420788e2238e6/NET%20Core/TestServer/Program.cs#L128

Security policy happens at a different level than username and password (transport vs application layers), so `NetDispatcher` won't provide that to `Application` per client. If all of that is fine, you don't need to modify anything other than the class you derive from `Application`.
