### ISSUE TITLE
Client can't connect, problably, due to a Nonce question, Error: BadUnknownResponse

### ISSUE THREAD

**Issue by this-claudio** [nauful/LibUA#83]
``Hi, how are you?

I am beginner in OPC UA protocol, but i was following another **Issues** to understand the reason that don't able the connection.

I have been a difficultly to implement a client, when the code arrive the this part:
`var createRes = client.CreateSession(appDesc, "urn:DemoApplication", 2000);`
It's returning: BadUnknownResponse

So, I catched the communicate between client/server with WireShark, and find this:

The Requisition:
![image](https://user-images.githubusercontent.com/65410959/173981776-9297d209-60e6-4144-b53b-1b420fd2272f.png)

The Answer:

![image](https://user-images.githubusercontent.com/65410959/173981880-1f8f9b4a-a0b0-470d-86fe-4163699317c8.png)

And in the instance of client, on config object I found this:

![image](https://user-images.githubusercontent.com/65410959/173982142-1eb39ba6-1ae2-4636-9b95-d648a49f1531.png)

I am using the OPC UA Prosys Simulator Server

Can You help me to implement this, to be honest this implementation is to a universit work, and I need to implement a OPCClient by to end of month :)

**Comment by nauful** [comment]
There won't be any nonce if security is set to none. Try a security mode that signs but doesn't encrypt.

**Comment by this-claudio** [comment]
Thanks!
