### ISSUE TITLE
Question: Array of complex types

### ISSUE THREAD

**Issue by generik0** [nauful/LibUA#84]
HI. Thanks for your awesome lib!

I have a model (S88):

```c#
public class Command
{
    public string UnitMode { get; set; }
    public bool UnitModeChangeRequest { get; set; }
    
    public string CntrlCmd { get; set; }
    public string CmdChangeRequest { get; set; }
}
```

And I need an array of 10 of them. Can you provide a hint as to the right direction, please?
Or would you recommend not using arrays, and having individual objects?

**Comment by nauful** [comment]
You might use the `MemoryBuffer` class to serialize your instances into a byte array, then set that as the body for an `ExtensionObject`. `DataValue` can accept that `ExtensionObject` instance with your serialized data as the value.

**Comment by generik0** [comment]
thx. i'll try
