### ISSUE TITLE
Structure data value for node

### ISSUE THREAD

**Issue by fch96733357** [nauful/LibUA#87]
Hi Nauful, There three values for each of my device node, 1st is rpm, 2ns is status and 3rd is velocity, how can I set a node value as structure like struct {public ushort rpm; public ushort status; public double velocity}

Thanks and best Regards
Feng

**Comment by nauful** [comment]
Hello Feng,

I would recommend one node per device with no value, but with a Parent relationship to three separate children tags, one for each field with a value.
