### ISSUE TITLE
Updated nuget package?

### ISSUE THREAD

**Issue by smitha-cgi** [nauful/LibUA#88]
Latest package available via nuget is 1.0.1 dated July 11 2020. Any chance you could publish a newer version? Would rather refer to a package than have to clone the repo and store the source with the rest of my app code.

**Comment by nauful** [comment]
You might be looking at a fork. The main branch has never published a nuget package. I will consider this when I have time to look at it.

**Comment by smitha-cgi** [comment]
Ah, no worries. The current package is pointing to your github page as the project website, so I guess davidguidali published it without your knowledge a few years ago.

![image](https://user-images.githubusercontent.com/66452735/180328202-4f9c804f-c3ad-478d-818a-33622dda922c.png)
