### ISSUE TITLE
Wrong MessageType.Error value in Types.cs

### ISSUE THREAD

**Issue by Ttberg** [nauful/LibUA#9]
I was trying to connect the client to the OPC foundation reference server, but was unable to connect. During my search as to why it wouldn't connect I found out I wasn't receiving the error message type of the server. The reference server uses ID 0x525245, and in the LibUA code I find ID 0x515145 (Line 39 in Types.cs). 

After I changed the ID into 0x525245 I was able to receive the error message and found out I was using a security policy which wasn't enabled on the server side.

**Comment by nauful** [comment]
Thanks, fixed. 0x525245 is ERR for the transport layer.
